---
author: Daniel W.A. Noble, Fonti Kar, Frank Seebacher Alex Bush, & Shinichi Nakagawa
date: "`r Sys.Date()`"
bibliography: refs.bib
csl: science.csl
output: 
  bookdown::html_document2:
    code_folding: hide
    number_sections: no
    toc: yes
    toc_depth: 6
    toc_float: yes
    bibliography: refs.bib
  bookdown::word_document2:
    toc: no
    toc_depth: 6
    number_sections: true
    reference_docx: template.docx
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, message = FALSE, warning = FALSE, tidy = TRUE, fig.width = 10)
## numbers >= 10^5 will be denoted in scientific notation,		  ## numbers >= 10^5 will be denoted in scientific notation,
  ## and rounded to 2 digits		  ## and rounded to 2 digits
  options(digits = 2)

##################################
# Clean workspace
##################################
    rm(list=ls())

##################################
# Loading packages & Functions
##################################
    pacman::p_load(tidyverse, kableExtra, gridExtra, magrittr, Hmisc, googlesheets4, metafor, stringr, formatR, rmarkdown, kableExtra, flextable, raster, rasterVis, rnoaa, sp, ggmap, patchwork, ggpubr, RColorBrewer, sf, ggtree, ape, phytools, viridis, ncdf4.helpers, ncdf4, PCICt, readr, chron, tmap, rgdal, MCMCglmm, brms, latex2exp)

#devtools::install_github(repo = "ErikKusch/KrigR")
## Function to produce colour palette
# Note that temp is stored as a factor of 10 C larger, so needs to be divided. Also, we can greate a custom colour palelte function using colorRampPallette
colfunc <- colorRampPalette(rev(brewer.pal(10,"RdBu")))
#test colfunc(10) will generate the exact Hex codes for 10 different colours can 10 to 100 and you get 100 colour hex codes. Very useful webpage: https://pjbartlein.github.io/REarthSysSci/rasterVis01.html

    # loading functions
    source("../R/functions.R")

```


```{r data_summary, echo = FALSE, results="hide"}

##########################
## Load processed datasets
##########################
data_wide <- read.csv("../output/data/data_final_wide.csv")
data_long <- read.csv("../output/data/data_final_long.csv")

##########################
## Summarise data
 data_wide$lat <- as.numeric(data_wide$lat)
    new_papers <- data_wide[-grep("_o", data_wide$record_num),]
    old_papers <- data_wide[grep("_o", data_wide$record_num),]
  
    
    # habitat
      spp_habitat <- data_wide %>%
                      group_by(habitat) %>%
                      summarise(spp_n = length(unique(species_full)))
      tot_spp <- sum(spp_habitat[,2])


```